---
title: Tyfu gwas-y-neidr
hero_image: images/banner.png
description: Dyma gyfle i ti greu gwas-y-neidr sy'n tyfu'n fwy wrth iddo fwyta pryfetach a mosgitos blîn.
pdf: resources/rpi-grow-a-dragonfly.pdf
meta_title: Scratch coding projects for kids and teens | Grow a dragonfly
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where a dragonfly grows bigger as it eats insects.
version: 4
listed: true
copyedit: false
last_tested: '2021-04-27'
steps:
  - 
    title: Byddi di'n creu
  - 
    title: Gosod yr olygfa
  - 
    title: Pryfyn i'w fwyta
    completion:
      - engaged
  - 
    title: Tyfu i llawn faint
  - 
    title: Symud yn well
  - 
    title: Mwy o fwyd
    completion:
      - internal
  - 
    title: Symudiad pryfyn ar hap
    challenge: true
  - 
    title: Cwis cyflym
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
