---
title: ಡ್ರಾಗನ್‌ಫ್ಲೈ ಬೆಳೆಸಿ
hero_image: images / banner.png
description: ಕಿರಿಕಿರಿ ಉಂಟುಮಾಡುವ ಸೊಳ್ಳೆಗಳನ್ನು ಮತ್ತು ಇತರ ಕೀಟಗಳನ್ನು ತಿನ್ನುತ್ತ ದೊಡ್ಡದಾಗಿ ಬೆಳೆಯುವ ಡ್ರಾಗನ್‌ಫ್ಲೈ ಮಾಡಿ.
meta_title: Scratch coding projects for kids and teens | Grow a dragonfly
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where a dragonfly grows bigger as it eats insects.
version: 4
listed: true
copyedit: false
last_tested: '2021-04-27'
steps:
  - 
    title: You will make
  - 
    title: ದೃಶ್ಯವನ್ನು ಹೊಂದಿಸಿ
  - 
    title: ತಿನ್ನಲು ಒಂದು ನೊಣ
    completion:
      - engaged
  - 
    title: ಪೂರ್ಣ ಗಾತ್ರಕ್ಕೆ ಬೆಳೆಸಿರಿ
  - 
    title: ಸುಧಾರಿತ ಚಲನೆ
  - 
    title: ಇನ್ನಷ್ಟು ಆಹಾರ
  - 
    title: ಯಾದೃಚ್ಛಿಕ ಕೀಟ ಚಲನೆ
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: ನಿಮ್ಮ ಪ್ರಾಜೆಕ್ಟ್‌ನ್ನು ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ
  - 
    title: ಮುಂದೆ ಏನು?
