---
title: Faire grandir une libellule
hero_image: images/banner.png
description: Crée une libellule qui grandit en mangeant les moustiques et autres insectes gênants.
pdf: resources/rpi-grow-a-dragonfly.pdf
meta_title: Scratch coding projects for kids and teens | Grow a dragonfly
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch app where a dragonfly grows bigger as it eats insects.
version: 4
listed: true
copyedit: false
last_tested: '2021-04-27'
steps:
  - title: Ce que tu vas faire
  - title: Créer la scène
  - title: Une mouche à manger
    completion:
      - engaged
  - title: Faire grandir jusqu'à sa taille maximale
  - title: Mouvement amélioré
  - title: Plus de nourriture
    completion:
      - internal
  - title: Défi
    challenge: true
  - title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
