---
title: Faire grandir une libellule
hero_image: images/banner.png
description: Crée une libellule qui grandit en mangeant les moustiques et autres insectes gênants.
pdf: resources/rpi-grow-a-dragonfly.pdf
meta_title: Projets de codage Scratch pour enfants et adolescents | Faire grandir une libellule
meta_description: Apprends Scratch grâce aux projets de codage de la Raspberry Pi Foundation destinés aux enfants et aux adolescents. Crée une application Scratch où une libellule grandit en mangeant des insectes.
version: 4
listed: true
copyedit: false
last_tested: '2021-04-27'
steps:
  - 
    title: Introduction
  - 
    title: Créer la scène
  - 
    title: Une mouche à manger
    completion:
      - engaged
  - 
    title: Faire grandir jusqu'à sa taille maximale
  - 
    title: Mouvement amélioré
  - 
    title: Plus de nourriture
    completion:
      - internal
  - 
    title: Défi
    challenge: true
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
